[package]
name = "daisy_bsp"
version = "0.0.2"
authors = ["Antoine van Gelder <antoine@flowdsp.io>"]
edition = "2018"
license = "AGPL-3.0-or-later"
description = "A board support package for the Electro-Smith Daisy Seed"
repository = "https://github.com/antoinevg/daisy_bsp"
documentation = "https://github.com/antoinevg/daisy_bsp/wiki"
categories = [
    "embedded",
    "hardware-support",
    "no-std",
]
keywords = [
    "cortex-m",
    "bsp",
    "stm32h7xx",
    "daisy",
]
readme = "README.md"

[package.metadata.docs.rs]
features = [ "seed", "pod", "petal", "patch", "field" ]
targets = ["thumbv7em-none-eabihf"]


# - dependencies --------------------------------------------------------------

[dependencies]
cortex-m = "0.6.3"
cortex-m-rt = { version = "0.6.13", features = ["device"] }

# branch = dma
stm32h7xx-hal = { features = [ "stm32h750v", "rt", "revision_v" ], git = "https://github.com/stm32-rs/stm32h7xx-hal.git", rev = "0bfeeca4ce120c1b7c6d140a7da73a4372b874d8"  }
#stm32h7xx-hal = { version = "0.8.0", features = [ "stm32h750v", "rt", "revision_v" ] }

heapless = { version = "0.5.6", default_features = false }
static-alloc = "0.2.1"
without-alloc = "0.2.1"
cty = "0.2.1"

[dependencies.dsp]
version = "0.1.0"
path = "../../seisiun-synth.git/dsp"
optional = true

[dependencies.instrument]
version = "0.1.0"
path = "../../seisiun-synth.git/instrument"
optional = true


# - dev dependencies ----------------------------------------------------------

[dev-dependencies]
panic-semihosting = { version = "0.5.3" }
cortex-m-semihosting = { version = "0.3.5" }


# - features ------------------------------------------------------------------

[features]
default = [ "seed" ]
seed = []
pod = []
petal = []
patch = []
field = []
uses_dsp = [ "dsp" ]
uses_instrument = [ "instrument" ]


# - profiles ------------------------------------------------------------------

[profile.dev]
debug = true
incremental = false
opt-level = "s" # optimize for binary size
#opt-level = 1
#opt-level = 0

[profile.release]
debug = true
opt-level = "s" #  optimize for binary size


# - examples ------------------------------------------------------------------

[[example]]
name = "blinky_pac"
required-features = ["seed"]

[[example]]
name = "blinky_hal"
required-features = ["seed"]

[[example]]
name = "blinky_bsp"
required-features = ["seed"]

[[example]]
name = "button"
required-features = ["seed"]

[[example]]
name = "audio_passthrough"
required-features = ["seed"]

[[example]]
name = "serial"
required-features = ["seed"]


# - adc20 examples ------------------------------------------------------------

[[example]]
name = "adc20_1"
required-features = ["seed"]

[[example]]
name = "adc20_2"
required-features = ["seed", "uses_dsp"]

[[example]]
name = "adc20_3"
required-features = ["seed", "uses_dsp", "uses_instrument"]

[[example]]
name = "adc20_typestates"
required-features = ["seed"]

[[example]]
name = "adc20_safety"
required-features = ["seed", "uses_dsp", "uses_instrument"]
